/* Automatically @generated by tree-sitter v0.25.9 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 78
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 47
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 9
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 7
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  anon_sym_effect = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_COLON = 5,
  anon_sym_DASH_GT = 6,
  anon_sym_COMMA = 7,
  aux_sym_type_param_token1 = 8,
  anon_sym_LPAREN_RPAREN = 9,
  anon_sym_LPAREN = 10,
  anon_sym_RPAREN = 11,
  anon_sym_data = 12,
  anon_sym_EQ = 13,
  anon_sym_SEMI = 14,
  anon_sym_PIPE = 15,
  sym_upper_ident = 16,
  sym_lower_ident = 17,
  anon_sym_let = 18,
  anon_sym_BSLASH = 19,
  anon_sym_in = 20,
  sym_variable = 21,
  sym_integer = 22,
  anon_sym_DQUOTE = 23,
  aux_sym_string_literal_token1 = 24,
  sym_source_file = 25,
  sym__top_level_item = 26,
  sym_effect_decl = 27,
  sym_effect_name = 28,
  sym_effect_op = 29,
  sym_type_param = 30,
  sym_type = 31,
  sym__type_seq = 32,
  sym__type_atom = 33,
  sym_type_constructor = 34,
  sym_data_decl = 35,
  sym_cstr_list = 36,
  sym_let_decl = 37,
  sym_expression = 38,
  sym_lambda = 39,
  sym_let_exp = 40,
  sym_string_literal = 41,
  aux_sym_source_file_repeat1 = 42,
  aux_sym_effect_decl_repeat1 = 43,
  aux_sym__type_seq_repeat1 = 44,
  aux_sym_cstr_list_repeat1 = 45,
  aux_sym_string_literal_repeat1 = 46,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [anon_sym_effect] = "effect",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_COMMA] = ",",
  [aux_sym_type_param_token1] = "type_param_token1",
  [anon_sym_LPAREN_RPAREN] = "()",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_data] = "data",
  [anon_sym_EQ] = "=",
  [anon_sym_SEMI] = ";",
  [anon_sym_PIPE] = "|",
  [sym_upper_ident] = "upper_ident",
  [sym_lower_ident] = "lower_ident",
  [anon_sym_let] = "let",
  [anon_sym_BSLASH] = "\\",
  [anon_sym_in] = "in",
  [sym_variable] = "variable",
  [sym_integer] = "integer",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_literal_token1] = "string_literal_token1",
  [sym_source_file] = "source_file",
  [sym__top_level_item] = "_top_level_item",
  [sym_effect_decl] = "effect_decl",
  [sym_effect_name] = "effect_name",
  [sym_effect_op] = "effect_op",
  [sym_type_param] = "type_param",
  [sym_type] = "type",
  [sym__type_seq] = "_type_seq",
  [sym__type_atom] = "_type_atom",
  [sym_type_constructor] = "type_constructor",
  [sym_data_decl] = "data_decl",
  [sym_cstr_list] = "cstr_list",
  [sym_let_decl] = "let_decl",
  [sym_expression] = "expression",
  [sym_lambda] = "lambda",
  [sym_let_exp] = "let_exp",
  [sym_string_literal] = "string_literal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_effect_decl_repeat1] = "effect_decl_repeat1",
  [aux_sym__type_seq_repeat1] = "_type_seq_repeat1",
  [aux_sym_cstr_list_repeat1] = "cstr_list_repeat1",
  [aux_sym_string_literal_repeat1] = "string_literal_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [anon_sym_effect] = anon_sym_effect,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [aux_sym_type_param_token1] = aux_sym_type_param_token1,
  [anon_sym_LPAREN_RPAREN] = anon_sym_LPAREN_RPAREN,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_data] = anon_sym_data,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [sym_upper_ident] = sym_upper_ident,
  [sym_lower_ident] = sym_lower_ident,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [anon_sym_in] = anon_sym_in,
  [sym_variable] = sym_variable,
  [sym_integer] = sym_integer,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_literal_token1] = aux_sym_string_literal_token1,
  [sym_source_file] = sym_source_file,
  [sym__top_level_item] = sym__top_level_item,
  [sym_effect_decl] = sym_effect_decl,
  [sym_effect_name] = sym_effect_name,
  [sym_effect_op] = sym_effect_op,
  [sym_type_param] = sym_type_param,
  [sym_type] = sym_type,
  [sym__type_seq] = sym__type_seq,
  [sym__type_atom] = sym__type_atom,
  [sym_type_constructor] = sym_type_constructor,
  [sym_data_decl] = sym_data_decl,
  [sym_cstr_list] = sym_cstr_list,
  [sym_let_decl] = sym_let_decl,
  [sym_expression] = sym_expression,
  [sym_lambda] = sym_lambda,
  [sym_let_exp] = sym_let_exp,
  [sym_string_literal] = sym_string_literal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_effect_decl_repeat1] = aux_sym_effect_decl_repeat1,
  [aux_sym__type_seq_repeat1] = aux_sym__type_seq_repeat1,
  [aux_sym_cstr_list_repeat1] = aux_sym_cstr_list_repeat1,
  [aux_sym_string_literal_repeat1] = aux_sym_string_literal_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_effect] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_type_param_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LPAREN_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_data] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym_upper_ident] = {
    .visible = true,
    .named = true,
  },
  [sym_lower_ident] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__top_level_item] = {
    .visible = false,
    .named = true,
  },
  [sym_effect_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_effect_name] = {
    .visible = true,
    .named = true,
  },
  [sym_effect_op] = {
    .visible = true,
    .named = true,
  },
  [sym_type_param] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym__type_seq] = {
    .visible = false,
    .named = true,
  },
  [sym__type_atom] = {
    .visible = false,
    .named = true,
  },
  [sym_type_constructor] = {
    .visible = true,
    .named = true,
  },
  [sym_data_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_cstr_list] = {
    .visible = true,
    .named = true,
  },
  [sym_let_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_lambda] = {
    .visible = true,
    .named = true,
  },
  [sym_let_exp] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_effect_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__type_seq_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_cstr_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_binding = 1,
  field_body = 2,
  field_cstr_list = 3,
  field_effect_name = 4,
  field_effect_op_name = 5,
  field_name = 6,
  field_type_name = 7,
  field_value = 8,
  field_var = 9,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_binding] = "binding",
  [field_body] = "body",
  [field_cstr_list] = "cstr_list",
  [field_effect_name] = "effect_name",
  [field_effect_op_name] = "effect_op_name",
  [field_name] = "name",
  [field_type_name] = "type_name",
  [field_value] = "value",
  [field_var] = "var",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 1},
  [4] = {.index = 5, .length = 2},
  [5] = {.index = 7, .length = 1},
  [6] = {.index = 8, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_cstr_list, 3},
    {field_type_name, 1},
  [2] =
    {field_name, 1},
    {field_value, 3},
  [4] =
    {field_effect_name, 1},
  [5] =
    {field_body, 3},
    {field_var, 1},
  [7] =
    {field_effect_op_name, 0},
  [8] =
    {field_binding, 3},
    {field_body, 5},
    {field_name, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 3,
  [6] = 4,
  [7] = 2,
  [8] = 2,
  [9] = 3,
  [10] = 4,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 18,
  [28] = 28,
  [29] = 18,
  [30] = 14,
  [31] = 31,
  [32] = 13,
  [33] = 15,
  [34] = 31,
  [35] = 31,
  [36] = 14,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 13,
  [41] = 15,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 28,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 62,
  [75] = 62,
  [76] = 76,
  [77] = 77,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(25);
      ADVANCE_MAP(
        '"', 59,
        '(', 43,
        ')', 44,
        ',', 36,
        '-', 11,
        '/', 6,
        ':', 34,
        ';', 47,
        '=', 46,
        '\\', 53,
        'd', 38,
        'e', 40,
        'l', 39,
        '{', 32,
        '|', 48,
        '}', 33,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(49);
      END_STATE();
    case 1:
      if (lookahead == '\r') ADVANCE(29);
      if (lookahead != 0) ADVANCE(28);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(59);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '\\') ADVANCE(53);
      if (lookahead == 'l') ADVANCE(55);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(59);
      if (lookahead == '/') ADVANCE(61);
      if (lookahead == '\\') ADVANCE(23);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(64);
      if (lookahead != 0) ADVANCE(65);
      END_STATE();
    case 4:
      if (lookahead == '(') ADVANCE(43);
      if (lookahead == ')') ADVANCE(44);
      if (lookahead == '-') ADVANCE(11);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '=') ADVANCE(46);
      if (lookahead == '{') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(49);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 5:
      if (lookahead == '(') ADVANCE(43);
      if (lookahead == ',') ADVANCE(36);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '}') ADVANCE(33);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(49);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '/') ADVANCE(28);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(7);
      if (lookahead == '/') ADVANCE(26);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 8:
      if (lookahead == '*') ADVANCE(7);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == ',') ADVANCE(36);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '}') ADVANCE(33);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(9);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 10:
      if (lookahead == '/') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(10);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 11:
      if (lookahead == '>') ADVANCE(35);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(20);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(45);
      END_STATE();
    case 14:
      if (lookahead == 'c') ADVANCE(22);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(14);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 17:
      if (lookahead == 'f') ADVANCE(18);
      END_STATE();
    case 18:
      if (lookahead == 'f') ADVANCE(15);
      END_STATE();
    case 19:
      if (lookahead == 'n') ADVANCE(54);
      END_STATE();
    case 20:
      if (lookahead == 't') ADVANCE(13);
      END_STATE();
    case 21:
      if (lookahead == 't') ADVANCE(51);
      END_STATE();
    case 22:
      if (lookahead == 't') ADVANCE(31);
      END_STATE();
    case 23:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(60);
      END_STATE();
    case 24:
      if (eof) ADVANCE(25);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == ';') ADVANCE(47);
      if (lookahead == 'd') ADVANCE(12);
      if (lookahead == 'e') ADVANCE(17);
      if (lookahead == 'i') ADVANCE(19);
      if (lookahead == 'l') ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n') ADVANCE(65);
      if (lookahead == '"') ADVANCE(28);
      if (lookahead == '\\') ADVANCE(1);
      if (lookahead != 0) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\\') ADVANCE(1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\\') ADVANCE(1);
      if (lookahead != 0) ADVANCE(28);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(65);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_effect);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_type_param_token1);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_type_param_token1);
      if (lookahead == 'a') ADVANCE(20);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_type_param_token1);
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_type_param_token1);
      if (lookahead == 'f') ADVANCE(18);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_type_param_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LPAREN_RPAREN);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      if (lookahead == ')') ADVANCE(42);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_data);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_upper_ident);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_lower_ident);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_let);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 'e') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == 't') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_variable);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '*') ADVANCE(63);
      if (lookahead == '/') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(65);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '*') ADVANCE(62);
      if (lookahead == '/') ADVANCE(30);
      if (lookahead == '"' ||
          lookahead == '\\') ADVANCE(8);
      if (lookahead != 0) ADVANCE(63);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '*') ADVANCE(62);
      if (lookahead == '"' ||
          lookahead == '\\') ADVANCE(8);
      if (lookahead != 0) ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '/') ADVANCE(61);
      if (lookahead == '\\') ADVANCE(23);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(64);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(65);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(65);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 4},
  [6] = {.lex_state = 4},
  [7] = {.lex_state = 5},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 5},
  [10] = {.lex_state = 5},
  [11] = {.lex_state = 4},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 4},
  [18] = {.lex_state = 4},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 4},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 4},
  [24] = {.lex_state = 4},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 4},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 4},
  [30] = {.lex_state = 4},
  [31] = {.lex_state = 4},
  [32] = {.lex_state = 4},
  [33] = {.lex_state = 4},
  [34] = {.lex_state = 4},
  [35] = {.lex_state = 4},
  [36] = {.lex_state = 5},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 5},
  [41] = {.lex_state = 5},
  [42] = {.lex_state = 24},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 24},
  [45] = {.lex_state = 24},
  [46] = {.lex_state = 24},
  [47] = {.lex_state = 24},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 9},
  [53] = {.lex_state = 9},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 9},
  [56] = {.lex_state = 3},
  [57] = {.lex_state = 3},
  [58] = {.lex_state = 9},
  [59] = {.lex_state = 3},
  [60] = {.lex_state = 9},
  [61] = {.lex_state = 9},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 10},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 10},
  [69] = {.lex_state = 10},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 24},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_effect] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [aux_sym_type_param_token1] = ACTIONS(1),
    [anon_sym_LPAREN_RPAREN] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_data] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [sym_upper_ident] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(76),
    [sym__top_level_item] = STATE(21),
    [sym_effect_decl] = STATE(21),
    [sym_data_decl] = STATE(21),
    [sym_let_decl] = STATE(21),
    [aux_sym_source_file_repeat1] = STATE(21),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [anon_sym_effect] = ACTIONS(7),
    [anon_sym_data] = ACTIONS(9),
    [anon_sym_let] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      aux_sym_type_param_token1,
    ACTIONS(17), 1,
      anon_sym_LPAREN_RPAREN,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      sym_upper_ident,
    STATE(3), 4,
      sym_type_param,
      sym__type_atom,
      sym_type_constructor,
      aux_sym__type_seq_repeat1,
    ACTIONS(13), 6,
      ts_builtin_sym_end,
      anon_sym_effect,
      anon_sym_data,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_let,
  [30] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      aux_sym_type_param_token1,
    ACTIONS(17), 1,
      anon_sym_LPAREN_RPAREN,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      sym_upper_ident,
    STATE(4), 4,
      sym_type_param,
      sym__type_atom,
      sym_type_constructor,
      aux_sym__type_seq_repeat1,
    ACTIONS(23), 6,
      ts_builtin_sym_end,
      anon_sym_effect,
      anon_sym_data,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_let,
  [60] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      aux_sym_type_param_token1,
    ACTIONS(30), 1,
      anon_sym_LPAREN_RPAREN,
    ACTIONS(33), 1,
      anon_sym_LPAREN,
    ACTIONS(36), 1,
      sym_upper_ident,
    STATE(4), 4,
      sym_type_param,
      sym__type_atom,
      sym_type_constructor,
      aux_sym__type_seq_repeat1,
    ACTIONS(25), 6,
      ts_builtin_sym_end,
      anon_sym_effect,
      anon_sym_data,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_let,
  [90] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      sym_upper_ident,
    ACTIONS(39), 2,
      aux_sym_type_param_token1,
      anon_sym_LPAREN_RPAREN,
    ACTIONS(23), 4,
      anon_sym_LBRACE,
      anon_sym_DASH_GT,
      anon_sym_RPAREN,
      anon_sym_EQ,
    STATE(6), 4,
      sym_type_param,
      sym__type_atom,
      sym_type_constructor,
      aux_sym__type_seq_repeat1,
  [116] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(48), 1,
      anon_sym_LPAREN,
    ACTIONS(51), 1,
      sym_upper_ident,
    ACTIONS(45), 2,
      aux_sym_type_param_token1,
      anon_sym_LPAREN_RPAREN,
    ACTIONS(25), 4,
      anon_sym_LBRACE,
      anon_sym_DASH_GT,
      anon_sym_RPAREN,
      anon_sym_EQ,
    STATE(6), 4,
      sym_type_param,
      sym__type_atom,
      sym_type_constructor,
      aux_sym__type_seq_repeat1,
  [142] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(54), 1,
      aux_sym_type_param_token1,
    ACTIONS(56), 1,
      anon_sym_LPAREN_RPAREN,
    ACTIONS(58), 1,
      anon_sym_LPAREN,
    ACTIONS(60), 1,
      sym_upper_ident,
    ACTIONS(62), 1,
      sym_lower_ident,
    ACTIONS(13), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
    STATE(9), 4,
      sym_type_param,
      sym__type_atom,
      sym_type_constructor,
      aux_sym__type_seq_repeat1,
  [171] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      sym_upper_ident,
    ACTIONS(39), 2,
      aux_sym_type_param_token1,
      anon_sym_LPAREN_RPAREN,
    ACTIONS(13), 3,
      anon_sym_LBRACE,
      anon_sym_DASH_GT,
      anon_sym_EQ,
    STATE(5), 4,
      sym_type_param,
      sym__type_atom,
      sym_type_constructor,
      aux_sym__type_seq_repeat1,
  [196] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(54), 1,
      aux_sym_type_param_token1,
    ACTIONS(56), 1,
      anon_sym_LPAREN_RPAREN,
    ACTIONS(58), 1,
      anon_sym_LPAREN,
    ACTIONS(60), 1,
      sym_upper_ident,
    ACTIONS(64), 1,
      sym_lower_ident,
    ACTIONS(23), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
    STATE(10), 4,
      sym_type_param,
      sym__type_atom,
      sym_type_constructor,
      aux_sym__type_seq_repeat1,
  [225] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      aux_sym_type_param_token1,
    ACTIONS(69), 1,
      anon_sym_LPAREN_RPAREN,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(75), 1,
      sym_upper_ident,
    ACTIONS(78), 1,
      sym_lower_ident,
    ACTIONS(25), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
    STATE(10), 4,
      sym_type_param,
      sym__type_atom,
      sym_type_constructor,
      aux_sym__type_seq_repeat1,
  [254] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      sym_upper_ident,
    STATE(28), 1,
      sym__type_seq,
    STATE(63), 1,
      sym_effect_name,
    STATE(72), 1,
      sym_type,
    ACTIONS(39), 2,
      aux_sym_type_param_token1,
      anon_sym_LPAREN_RPAREN,
    STATE(8), 3,
      sym_type_param,
      sym__type_atom,
      sym_type_constructor,
  [282] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      sym_upper_ident,
    STATE(28), 1,
      sym__type_seq,
    STATE(39), 1,
      sym_type,
    STATE(48), 1,
      sym_cstr_list,
    ACTIONS(17), 2,
      aux_sym_type_param_token1,
      anon_sym_LPAREN_RPAREN,
    STATE(2), 3,
      sym_type_param,
      sym__type_atom,
      sym_type_constructor,
  [310] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 2,
      aux_sym_type_param_token1,
      anon_sym_LPAREN,
    ACTIONS(80), 8,
      ts_builtin_sym_end,
      anon_sym_effect,
      anon_sym_LPAREN_RPAREN,
      anon_sym_data,
      anon_sym_SEMI,
      anon_sym_PIPE,
      sym_upper_ident,
      anon_sym_let,
  [328] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 2,
      aux_sym_type_param_token1,
      anon_sym_LPAREN,
    ACTIONS(84), 8,
      ts_builtin_sym_end,
      anon_sym_effect,
      anon_sym_LPAREN_RPAREN,
      anon_sym_data,
      anon_sym_SEMI,
      anon_sym_PIPE,
      sym_upper_ident,
      anon_sym_let,
  [346] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 2,
      aux_sym_type_param_token1,
      anon_sym_LPAREN,
    ACTIONS(88), 8,
      ts_builtin_sym_end,
      anon_sym_effect,
      anon_sym_LPAREN_RPAREN,
      anon_sym_data,
      anon_sym_SEMI,
      anon_sym_PIPE,
      sym_upper_ident,
      anon_sym_let,
  [364] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 1,
      ts_builtin_sym_end,
    ACTIONS(94), 1,
      anon_sym_effect,
    ACTIONS(97), 1,
      anon_sym_data,
    ACTIONS(100), 1,
      anon_sym_let,
    STATE(16), 5,
      sym__top_level_item,
      sym_effect_decl,
      sym_data_decl,
      sym_let_decl,
      aux_sym_source_file_repeat1,
  [387] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      sym_upper_ident,
    STATE(28), 1,
      sym__type_seq,
    STATE(66), 1,
      sym_type,
    ACTIONS(39), 2,
      aux_sym_type_param_token1,
      anon_sym_LPAREN_RPAREN,
    STATE(8), 3,
      sym_type_param,
      sym__type_atom,
      sym_type_constructor,
  [412] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      sym_upper_ident,
    ACTIONS(103), 1,
      anon_sym_RPAREN,
    ACTIONS(39), 2,
      aux_sym_type_param_token1,
      anon_sym_LPAREN_RPAREN,
    STATE(5), 4,
      sym_type_param,
      sym__type_atom,
      sym_type_constructor,
      aux_sym__type_seq_repeat1,
  [435] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      anon_sym_let,
    ACTIONS(107), 1,
      anon_sym_BSLASH,
    ACTIONS(109), 1,
      sym_variable,
    ACTIONS(111), 1,
      sym_integer,
    ACTIONS(113), 1,
      anon_sym_DQUOTE,
    STATE(49), 1,
      sym_expression,
    STATE(47), 3,
      sym_lambda,
      sym_let_exp,
      sym_string_literal,
  [462] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      sym_upper_ident,
    STATE(28), 1,
      sym__type_seq,
    STATE(64), 1,
      sym_type,
    ACTIONS(39), 2,
      aux_sym_type_param_token1,
      anon_sym_LPAREN_RPAREN,
    STATE(8), 3,
      sym_type_param,
      sym__type_atom,
      sym_type_constructor,
  [487] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_effect,
    ACTIONS(9), 1,
      anon_sym_data,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(115), 1,
      ts_builtin_sym_end,
    STATE(16), 5,
      sym__top_level_item,
      sym_effect_decl,
      sym_data_decl,
      sym_let_decl,
      aux_sym_source_file_repeat1,
  [510] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      anon_sym_let,
    ACTIONS(107), 1,
      anon_sym_BSLASH,
    ACTIONS(109), 1,
      sym_variable,
    ACTIONS(111), 1,
      sym_integer,
    ACTIONS(113), 1,
      anon_sym_DQUOTE,
    STATE(77), 1,
      sym_expression,
    STATE(47), 3,
      sym_lambda,
      sym_let_exp,
      sym_string_literal,
  [537] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      sym_upper_ident,
    STATE(28), 1,
      sym__type_seq,
    STATE(43), 1,
      sym_type,
    ACTIONS(17), 2,
      aux_sym_type_param_token1,
      anon_sym_LPAREN_RPAREN,
    STATE(2), 3,
      sym_type_param,
      sym__type_atom,
      sym_type_constructor,
  [562] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      anon_sym_LPAREN,
    ACTIONS(60), 1,
      sym_upper_ident,
    STATE(58), 1,
      sym_type,
    STATE(60), 1,
      sym__type_seq,
    ACTIONS(56), 2,
      aux_sym_type_param_token1,
      anon_sym_LPAREN_RPAREN,
    STATE(7), 3,
      sym_type_param,
      sym__type_atom,
      sym_type_constructor,
  [587] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      anon_sym_let,
    ACTIONS(107), 1,
      anon_sym_BSLASH,
    ACTIONS(109), 1,
      sym_variable,
    ACTIONS(111), 1,
      sym_integer,
    ACTIONS(113), 1,
      anon_sym_DQUOTE,
    STATE(45), 1,
      sym_expression,
    STATE(47), 3,
      sym_lambda,
      sym_let_exp,
      sym_string_literal,
  [614] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      anon_sym_let,
    ACTIONS(107), 1,
      anon_sym_BSLASH,
    ACTIONS(109), 1,
      sym_variable,
    ACTIONS(111), 1,
      sym_integer,
    ACTIONS(113), 1,
      anon_sym_DQUOTE,
    STATE(46), 1,
      sym_expression,
    STATE(47), 3,
      sym_lambda,
      sym_let_exp,
      sym_string_literal,
  [641] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      sym_upper_ident,
    ACTIONS(117), 1,
      anon_sym_RPAREN,
    ACTIONS(39), 2,
      aux_sym_type_param_token1,
      anon_sym_LPAREN_RPAREN,
    STATE(5), 4,
      sym_type_param,
      sym__type_atom,
      sym_type_constructor,
      aux_sym__type_seq_repeat1,
  [664] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 9,
      ts_builtin_sym_end,
      anon_sym_effect,
      anon_sym_LBRACE,
      anon_sym_DASH_GT,
      anon_sym_data,
      anon_sym_EQ,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_let,
  [679] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      sym_upper_ident,
    ACTIONS(119), 1,
      anon_sym_RPAREN,
    ACTIONS(39), 2,
      aux_sym_type_param_token1,
      anon_sym_LPAREN_RPAREN,
    STATE(5), 4,
      sym_type_param,
      sym__type_atom,
      sym_type_constructor,
      aux_sym__type_seq_repeat1,
  [702] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      anon_sym_LPAREN,
    ACTIONS(84), 7,
      anon_sym_LBRACE,
      anon_sym_DASH_GT,
      aux_sym_type_param_token1,
      anon_sym_LPAREN_RPAREN,
      anon_sym_RPAREN,
      anon_sym_EQ,
      sym_upper_ident,
  [718] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      sym_upper_ident,
    STATE(75), 1,
      sym__type_seq,
    ACTIONS(39), 2,
      aux_sym_type_param_token1,
      anon_sym_LPAREN_RPAREN,
    STATE(18), 3,
      sym_type_param,
      sym__type_atom,
      sym_type_constructor,
  [740] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 7,
      anon_sym_LBRACE,
      anon_sym_DASH_GT,
      aux_sym_type_param_token1,
      anon_sym_LPAREN_RPAREN,
      anon_sym_RPAREN,
      anon_sym_EQ,
      sym_upper_ident,
  [756] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 1,
      anon_sym_LPAREN,
    ACTIONS(88), 7,
      anon_sym_LBRACE,
      anon_sym_DASH_GT,
      aux_sym_type_param_token1,
      anon_sym_LPAREN_RPAREN,
      anon_sym_RPAREN,
      anon_sym_EQ,
      sym_upper_ident,
  [772] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      sym_upper_ident,
    STATE(62), 1,
      sym__type_seq,
    ACTIONS(39), 2,
      aux_sym_type_param_token1,
      anon_sym_LPAREN_RPAREN,
    STATE(29), 3,
      sym_type_param,
      sym__type_atom,
      sym_type_constructor,
  [794] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      sym_upper_ident,
    STATE(74), 1,
      sym__type_seq,
    ACTIONS(39), 2,
      aux_sym_type_param_token1,
      anon_sym_LPAREN_RPAREN,
    STATE(27), 3,
      sym_type_param,
      sym__type_atom,
      sym_type_constructor,
  [816] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 3,
      aux_sym_type_param_token1,
      anon_sym_LPAREN,
      sym_lower_ident,
    ACTIONS(84), 4,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_LPAREN_RPAREN,
      sym_upper_ident,
  [831] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      anon_sym_PIPE,
    STATE(38), 1,
      aux_sym_cstr_list_repeat1,
    ACTIONS(121), 5,
      ts_builtin_sym_end,
      anon_sym_effect,
      anon_sym_data,
      anon_sym_SEMI,
      anon_sym_let,
  [848] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      anon_sym_PIPE,
    STATE(38), 1,
      aux_sym_cstr_list_repeat1,
    ACTIONS(125), 5,
      ts_builtin_sym_end,
      anon_sym_effect,
      anon_sym_data,
      anon_sym_SEMI,
      anon_sym_let,
  [865] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      anon_sym_PIPE,
    STATE(37), 1,
      aux_sym_cstr_list_repeat1,
    ACTIONS(130), 5,
      ts_builtin_sym_end,
      anon_sym_effect,
      anon_sym_data,
      anon_sym_SEMI,
      anon_sym_let,
  [882] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 3,
      aux_sym_type_param_token1,
      anon_sym_LPAREN,
      sym_lower_ident,
    ACTIONS(80), 4,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_LPAREN_RPAREN,
      sym_upper_ident,
  [897] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 3,
      aux_sym_type_param_token1,
      anon_sym_LPAREN,
      sym_lower_ident,
    ACTIONS(88), 4,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_LPAREN_RPAREN,
      sym_upper_ident,
  [912] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 6,
      ts_builtin_sym_end,
      anon_sym_effect,
      anon_sym_data,
      anon_sym_SEMI,
      anon_sym_let,
      anon_sym_in,
  [924] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 6,
      ts_builtin_sym_end,
      anon_sym_effect,
      anon_sym_data,
      anon_sym_SEMI,
      anon_sym_PIPE,
      anon_sym_let,
  [936] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 6,
      ts_builtin_sym_end,
      anon_sym_effect,
      anon_sym_data,
      anon_sym_SEMI,
      anon_sym_let,
      anon_sym_in,
  [948] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 6,
      ts_builtin_sym_end,
      anon_sym_effect,
      anon_sym_data,
      anon_sym_SEMI,
      anon_sym_let,
      anon_sym_in,
  [960] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 6,
      ts_builtin_sym_end,
      anon_sym_effect,
      anon_sym_data,
      anon_sym_SEMI,
      anon_sym_let,
      anon_sym_in,
  [972] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 6,
      ts_builtin_sym_end,
      anon_sym_effect,
      anon_sym_data,
      anon_sym_SEMI,
      anon_sym_let,
      anon_sym_in,
  [984] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 1,
      anon_sym_SEMI,
    ACTIONS(142), 4,
      ts_builtin_sym_end,
      anon_sym_effect,
      anon_sym_data,
      anon_sym_let,
  [997] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      anon_sym_SEMI,
    ACTIONS(146), 4,
      ts_builtin_sym_end,
      anon_sym_effect,
      anon_sym_data,
      anon_sym_let,
  [1010] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 4,
      ts_builtin_sym_end,
      anon_sym_effect,
      anon_sym_data,
      anon_sym_let,
  [1020] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 4,
      ts_builtin_sym_end,
      anon_sym_effect,
      anon_sym_data,
      anon_sym_let,
  [1030] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 1,
      anon_sym_RBRACE,
    ACTIONS(156), 1,
      sym_lower_ident,
    STATE(52), 2,
      sym_effect_op,
      aux_sym_effect_decl_repeat1,
  [1044] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      anon_sym_RBRACE,
    ACTIONS(161), 1,
      sym_lower_ident,
    STATE(52), 2,
      sym_effect_op,
      aux_sym_effect_decl_repeat1,
  [1058] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 4,
      ts_builtin_sym_end,
      anon_sym_effect,
      anon_sym_data,
      anon_sym_let,
  [1068] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      sym_lower_ident,
    STATE(53), 2,
      sym_effect_op,
      aux_sym_effect_decl_repeat1,
  [1079] = 4,
    ACTIONS(165), 1,
      sym_comment,
    ACTIONS(167), 1,
      anon_sym_DQUOTE,
    ACTIONS(169), 1,
      aux_sym_string_literal_token1,
    STATE(57), 1,
      aux_sym_string_literal_repeat1,
  [1092] = 4,
    ACTIONS(165), 1,
      sym_comment,
    ACTIONS(171), 1,
      anon_sym_DQUOTE,
    ACTIONS(173), 1,
      aux_sym_string_literal_token1,
    STATE(57), 1,
      aux_sym_string_literal_repeat1,
  [1105] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 1,
      anon_sym_COMMA,
    ACTIONS(176), 2,
      anon_sym_RBRACE,
      sym_lower_ident,
  [1116] = 4,
    ACTIONS(165), 1,
      sym_comment,
    ACTIONS(180), 1,
      anon_sym_DQUOTE,
    ACTIONS(182), 1,
      aux_sym_string_literal_token1,
    STATE(56), 1,
      aux_sym_string_literal_repeat1,
  [1129] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(13), 3,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      sym_lower_ident,
  [1138] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 2,
      anon_sym_RBRACE,
      sym_lower_ident,
  [1146] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 1,
      anon_sym_RPAREN,
  [1153] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      anon_sym_LBRACE,
  [1160] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      anon_sym_DASH_GT,
  [1167] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 1,
      sym_variable,
  [1174] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 1,
      anon_sym_EQ,
  [1181] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(194), 1,
      anon_sym_DASH_GT,
  [1188] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 1,
      sym_variable,
  [1195] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 1,
      sym_variable,
  [1202] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      anon_sym_EQ,
  [1209] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 1,
      anon_sym_EQ,
  [1216] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      anon_sym_LBRACE,
  [1223] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 1,
      anon_sym_COLON,
  [1230] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      anon_sym_RPAREN,
  [1237] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      anon_sym_RPAREN,
  [1244] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      ts_builtin_sym_end,
  [1251] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      anon_sym_in,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 30,
  [SMALL_STATE(4)] = 60,
  [SMALL_STATE(5)] = 90,
  [SMALL_STATE(6)] = 116,
  [SMALL_STATE(7)] = 142,
  [SMALL_STATE(8)] = 171,
  [SMALL_STATE(9)] = 196,
  [SMALL_STATE(10)] = 225,
  [SMALL_STATE(11)] = 254,
  [SMALL_STATE(12)] = 282,
  [SMALL_STATE(13)] = 310,
  [SMALL_STATE(14)] = 328,
  [SMALL_STATE(15)] = 346,
  [SMALL_STATE(16)] = 364,
  [SMALL_STATE(17)] = 387,
  [SMALL_STATE(18)] = 412,
  [SMALL_STATE(19)] = 435,
  [SMALL_STATE(20)] = 462,
  [SMALL_STATE(21)] = 487,
  [SMALL_STATE(22)] = 510,
  [SMALL_STATE(23)] = 537,
  [SMALL_STATE(24)] = 562,
  [SMALL_STATE(25)] = 587,
  [SMALL_STATE(26)] = 614,
  [SMALL_STATE(27)] = 641,
  [SMALL_STATE(28)] = 664,
  [SMALL_STATE(29)] = 679,
  [SMALL_STATE(30)] = 702,
  [SMALL_STATE(31)] = 718,
  [SMALL_STATE(32)] = 740,
  [SMALL_STATE(33)] = 756,
  [SMALL_STATE(34)] = 772,
  [SMALL_STATE(35)] = 794,
  [SMALL_STATE(36)] = 816,
  [SMALL_STATE(37)] = 831,
  [SMALL_STATE(38)] = 848,
  [SMALL_STATE(39)] = 865,
  [SMALL_STATE(40)] = 882,
  [SMALL_STATE(41)] = 897,
  [SMALL_STATE(42)] = 912,
  [SMALL_STATE(43)] = 924,
  [SMALL_STATE(44)] = 936,
  [SMALL_STATE(45)] = 948,
  [SMALL_STATE(46)] = 960,
  [SMALL_STATE(47)] = 972,
  [SMALL_STATE(48)] = 984,
  [SMALL_STATE(49)] = 997,
  [SMALL_STATE(50)] = 1010,
  [SMALL_STATE(51)] = 1020,
  [SMALL_STATE(52)] = 1030,
  [SMALL_STATE(53)] = 1044,
  [SMALL_STATE(54)] = 1058,
  [SMALL_STATE(55)] = 1068,
  [SMALL_STATE(56)] = 1079,
  [SMALL_STATE(57)] = 1092,
  [SMALL_STATE(58)] = 1105,
  [SMALL_STATE(59)] = 1116,
  [SMALL_STATE(60)] = 1129,
  [SMALL_STATE(61)] = 1138,
  [SMALL_STATE(62)] = 1146,
  [SMALL_STATE(63)] = 1153,
  [SMALL_STATE(64)] = 1160,
  [SMALL_STATE(65)] = 1167,
  [SMALL_STATE(66)] = 1174,
  [SMALL_STATE(67)] = 1181,
  [SMALL_STATE(68)] = 1188,
  [SMALL_STATE(69)] = 1195,
  [SMALL_STATE(70)] = 1202,
  [SMALL_STATE(71)] = 1209,
  [SMALL_STATE(72)] = 1216,
  [SMALL_STATE(73)] = 1223,
  [SMALL_STATE(74)] = 1230,
  [SMALL_STATE(75)] = 1237,
  [SMALL_STATE(76)] = 1244,
  [SMALL_STATE(77)] = 1251,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type_seq, 2, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__type_seq_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__type_seq_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__type_seq_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__type_seq_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__type_seq_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__type_seq_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__type_seq_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__type_seq_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__type_seq, 2, 0, 0),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__type_seq_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__type_seq_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [72] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__type_seq_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__type_seq_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__type_seq_repeat1, 2, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_param, 1, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_param, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type_atom, 3, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__type_atom, 3, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_constructor, 1, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_constructor, 1, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [94] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [97] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [100] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cstr_list, 2, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_cstr_list_repeat1, 2, 0, 0),
  [127] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_cstr_list_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cstr_list, 1, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 2, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lambda, 4, 0, 4),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_exp, 6, 0, 6),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data_decl, 4, 0, 1),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_decl, 4, 0, 2),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data_decl, 5, 0, 1),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_decl, 5, 0, 2),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_effect_decl_repeat1, 2, 0, 0),
  [156] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_effect_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_effect_decl, 5, 0, 3),
  [165] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [167] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [169] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0),
  [173] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_effect_op, 5, 0, 5),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [180] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [182] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_effect_op, 6, 0, 5),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_effect_name, 1, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [208] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_row(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "row",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
